### ISSUE TITLE
pam_2fa patches vs. RHEL 7.4 and Damien Miller's alternate patch

### ISSUE THREAD

**Issue by timmooney** [CERN-CERT/pam_2fa#2]
These patches are fantastic and I thank you for providing them and [the pam_2fa site](https://cern-cert.github.io/pam_2fa/) .  The site alone made it easy to explain to management the value of running a patched openssh to get truly-working 2FA with either pubkey or GSSAPI as the first factor.

Since these patches were created, there have been two interesting developments:

- it appears that RHEL 7.4 (in beta now, release imminent) will be switching from openssh 6.6.1p1 all the way to openssh 7.4p1.  When RHEL 7.4 launches, will there be an effort to update the patches for it?

- Damien Miller has posted an alternate patch in [openssh bug 2408](https://bugzilla.mindrot.org/show_bug.cgi?id=2408) .  Has there been any discussion within CERN about the merits of his patch vs. yours?

Thanks,

Tim

**Comment by Feandil** [comment]
Hi Tim,

Glad to know that our work has been helpful outside of our organization!

On your questions:
- The patch was initially written for upstream OpenSSH version 7.2p1, to be included at upstream, before being backported to RedHat's OpenSSH version, so rebasing should not be that difficult. I have not checked the OpenSSH package in RHEL 7.4 yet but please note that our patch was included in RHEL 7.3 (see https://git.centos.org/blob/rpms!openssh.git/c7/SOURCES!openssh-6.6p1-expose-auth-information.patch). In any case, as we are relying internally on the feature, we will update the patch if the feature was removed in RHEL 7.4 (will have to check).
- Yes, I saw that he rewrote it. I have yet to answer him on this patch because I had no time to check the whole patch and test the results on a RHEL 7 system. However, from what I had time to see, I believe his patch is much cleaner by unifying our patch with the existing ssh key handling. I would say that the main reason our patch was different was that as we are not maintainers for OpenSHH, we can't not propose such a large rewrite for a new feature, we had to keep it simple and not touch existing features too much. From the point of view of PAM, the patch mostly includes minor changes in the output format that sounds fine.

Did that answer your questions?
Vincent

**Comment by timmooney** [comment]
Hi Vincent!

Yeah, I discovered yesterday when I started looking at applying your patch to openssh from RHEL 7.3 that a version of it was already included.  That was a pleasant surprise.  I also expect that it means that the rebased openssh in RHEL 7.4 will also have the patch, to minimize any backward compatibility issues.

It might be nice if the [https://cern-cert.github.io/pam_2fa/](https://cern-cert.github.io/pam_2fa/) site were updated to note that your patches are already included in RHEL 7.3's openssh, but it's probably also worth waiting to do that until 7.4 is out and we see whether that's still true.  I sure hope it is.

Thanks again for sharing the patches and putting up the pam_2fa site, it's extremely useful.
